---

- name: msmtp | package
  tags:
    - package
  package:
    name: msmtp-mta

- name: msmtp | remove other MTAs
  tags:
    - package
  package:
    state: absent
    purge: yes
    name: 
      - sendmail-base
      - sendmail-cf
      - sendmail-doc
      - exim4-base
      - exim4-config

- name: msmtp | config
  tags:
    - mail
    - config
  template:
    src: "{{ item }}.j2"
    dest: "/etc/{{ item }}"
    group: www-data
    mode: 0640
  with_items:
    - msmtprc
    - aliases
